version: '3.8'

services:
  log-api:
    build: .
    container_name: log-api
    restart: always
    ports:
      - "3000:3000"
    volumes:
      # Montamos o socket do Docker da VPS dentro do container do app
      # Isso permite que a API fale com o Docker Engine que roda na sua VPS
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - NODE_ENV=production
